# Books Seed Data - Dog Training & Behavior Library
# All books are created as default books (user_id: nil, is_default: true)

puts 'Seeding default books...'

books_data = [
  # CATEGORY 1: CPDT-KA CERTIFICATION ESSENTIALS
  {
    title: 'The Culture Clash (2nd Edition)',
    author: 'Jean Donaldson',
    publisher: 'James & Kenneth Publishers',
    year: 2005,
    pages: 224,
    isbn: '978-1888047059',
    price_range: '$15-20',
    format: 'Paperback, Kindle',
    category: 'CPDT-KA Certification Essentials',
    description: 'The definitive introduction to modern, science-based dog training. Donaldson dismantles outdated dominance theory and explains dog behavior through the lens of learning theory. Required reading for CPDT-KA certification. Covers: operant and classical conditioning, punishment vs. reinforcement, common behavior problems, and how dogs actually learn. Written in an engaging, sometimes humorous style that makes complex concepts accessible. This is THE book that changed dog training from dominance-based to science-based methods.',
    why_you_need_it: 'Foundation for certification exam. Every concept tested on CPDT-KA is rooted in principles from this book.',
    best_for: 'Certification prep, foundational understanding, challenging old myths',
    purchase_url: 'https://www.amazon.com/Culture-Clash-Jean-Donaldson/dp/1888047054',
    audible_url: nil
  },
  {
    title: "Don't Shoot the Dog! The New Art of Teaching and Training",
    author: 'Karen Pryor',
    publisher: 'Ringpress Books',
    year: 2019,
    pages: 256,
    isbn: '978-1860542985',
    price_range: '$16-22',
    format: 'Paperback, Kindle, Audiobook',
    category: 'CPDT-KA Certification Essentials',
    description: 'The classic book that brought operant conditioning and clicker training to the mainstream. Pryor, a marine mammal trainer, explains the four quadrants of operant conditioning, shaping behavior, and positive reinforcement techniques. Not dog-specific (covers training all species, including humans), which makes the principles even clearer. Practical examples throughout. The revised edition includes updated research and modern applications.',
    why_you_need_it: 'Core learning theory for CPDT-KA. Explains WHY positive reinforcement works better than punishment. Directly tested material.',
    best_for: 'Understanding learning theory, clicker training foundations, behavior shaping',
    purchase_url: 'https://www.amazon.com/Dont-Shoot-Dog-Teaching-Training/dp/1860542980',
    audible_url: 'https://www.audible.com/pd/Dont-Shoot-the-Dog-Audiobook/B002V8HFZC'
  },
  {
    title: 'Excel-erated Learning: Explaining in Plain English How Dogs Learn and How Best to Teach Them',
    author: 'Pamela J. Reid, PhD',
    publisher: 'James & Kenneth Publishers',
    year: 1996,
    pages: 167,
    isbn: '978-0966836226',
    price_range: '$18-25',
    format: 'Paperback',
    category: 'CPDT-KA Certification Essentials',
    description: "More technical deep dive into canine learning theory and cognition. Reid has a PhD in psychology and applies rigorous scientific principles to dog training. Covers: classical and operant conditioning in depth, cognitive abilities of dogs, memory and discrimination learning, motivation, and effective communication. Includes charts, diagrams, and research references. Denser read than Culture Clash but essential for understanding the 'why' behind training methods.",
    why_you_need_it: 'CPDT-KA exam tests detailed knowledge of learning theory. This book provides the depth needed to ace those questions.',
    best_for: 'Deep learning theory understanding, certification exam prep, scientific foundations',
    purchase_url: 'https://www.amazon.com/Excel-erated-Learning-Explaining-English-Learn/dp/0966836227',
    audible_url: nil
  },
  {
    title: 'Behavior Adjustment Training (BAT 2.0): New Practical Techniques for Fear, Frustration, and Aggression in Dogs',
    author: 'Grisha Stewart, MA, CPDT-KA',
    publisher: 'Dogwise Publishing',
    year: 2016,
    pages: 376,
    isbn: '978-1617812705',
    price_range: '$25-30',
    format: 'Paperback, Kindle',
    category: 'CPDT-KA Certification Essentials',
    description: 'The definitive guide to BAT (Behavior Adjustment Training), a force-free method for helping reactive and aggressive dogs. Stewart, a certified dog trainer and behavior consultant, developed this empowerment-based approach that allows dogs to learn through natural consequences and choice. Covers: identifying triggers, reading body language, creating effective setups, gradual desensitization techniques, and case studies. Essential for anyone working with reactive dogs in urban environments.',
    why_you_need_it: 'BAT is a key methodology tested on CPDT-KA exam. Critical for working with urban dogs who encounter triggers daily.',
    best_for: 'Reactivity protocols, leash aggression, fear-based behaviors, certification prep',
    purchase_url: 'https://www.amazon.com/Behavior-Adjustment-Training-Frustration-Aggression/dp/1617812706',
    audible_url: nil
  },
  {
    title: 'How Dogs Learn',
    author: 'Mary R. Burch, PhD & Jon S. Bailey, PhD',
    publisher: 'Howell Book House',
    year: 1999,
    pages: 224,
    isbn: '978-0876057845',
    price_range: '$15-20',
    format: 'Paperback, Kindle',
    category: 'CPDT-KA Certification Essentials',
    description: 'Comprehensive textbook-style guide to learning theory as applied to dogs. Written by two PhDs in psychology/behavior analysis. Covers: thorough breakdown of classical and operant conditioning, schedules of reinforcement, extinction, generalization, discrimination, chaining behaviors, and troubleshooting common problems. More academic in tone but highly readable. Includes practical training exercises and clear explanations of complex concepts.',
    why_you_need_it: 'CPDT-KA exam relies heavily on detailed learning theory questions. This book explains every concept thoroughly.',
    best_for: 'Certification exam prep, deep understanding of behavior principles, troubleshooting training issues',
    purchase_url: 'https://www.amazon.com/How-Dogs-Learn-Howell-Reference/dp/0876057845',
    audible_url: nil
  },
  {
    title: 'CPDT-KA Study Guide',
    author: 'Certification Council for Professional Dog Trainers',
    publisher: 'CCPDT',
    year: 2024,
    pages: nil,
    isbn: nil,
    price_range: 'Free with application',
    format: 'PDF',
    category: 'CPDT-KA Certification Essentials',
    description: 'Official study guide from CCPDT outlining all exam content areas, learning objectives, and recommended knowledge areas. Includes: exam format, breakdown of question distribution across topics, sample questions, and detailed content outline. Essential companion to your exam prep. Covers all 12 domains tested on the exam: Learning Theory, Ethology, Equipment, Instruction Skills, Husbandry, and more.',
    why_you_need_it: 'Official exam blueprint. Use this to guide your study plan and ensure you cover all tested areas.',
    best_for: 'Exam preparation structure, identifying knowledge gaps, understanding exam format',
    purchase_url: 'https://www.ccpdt.org/certification/dog-trainer/',
    audible_url: nil
  },

  # CATEGORY 2: DOG PSYCHOLOGY & COGNITION
  {
    title: 'Inside of a Dog: What Dogs See, Smell, and Know',
    author: 'Alexandra Horowitz, PhD',
    publisher: 'Scribner',
    year: 2009,
    pages: 368,
    isbn: '978-1416583431',
    price_range: '$15-18',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Dog Psychology & Cognition',
    description: "Cognitive scientist and dog lover Horowitz takes readers inside the mind and sensory world of dogs. Explores: canine olfaction (sense of smell), how dogs perceive time, what they understand about human emotions, theory of mind, play behavior, and attention. Beautifully written, scientifically rigorous, and deeply empathetic. Changes how you see your dog's experience of the world.",
    why_you_need_it: 'Understanding the canine umwelt (perceptual world) makes you a better trainer. Essential context for urban dog walkers.',
    best_for: 'Deepening empathy for dogs, understanding sensory experience, enrichment ideas',
    purchase_url: 'https://www.amazon.com/Inside-Dog-What-Dogs-Smell/dp/1416583432',
    audible_url: 'https://www.audible.com/pd/Inside-of-a-Dog-Audiobook/B002UZYX4C'
  },
  {
    title: 'The Emotional Lives of Animals: A Leading Scientist Explores Animal Joy, Sorrow, and Empathy',
    author: 'Marc Bekoff, PhD',
    publisher: 'New World Library',
    year: 2007,
    pages: 224,
    isbn: '978-1577315872',
    price_range: '$14-18',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Dog Psychology & Cognition',
    description: 'Renowned biologist Marc Bekoff presents evidence for complex emotional lives in animals, with particular focus on dogs. Covers: joy, grief, empathy, fairness, forgiveness, and moral behavior in animals. Combines scientific research with touching anecdotes. Bekoff argues convincingly that emotions evolved for survival and are present across species. Important reading for anyone who works with animals professionally.',
    why_you_need_it: 'Validates emotional reality of dogs, supports force-free training philosophy, helps explain behavior.',
    best_for: 'Ethical foundations of training, understanding emotional triggers, client education',
    purchase_url: 'https://www.amazon.com/Emotional-Lives-Animals-Leading-Scientist/dp/1577315871',
    audible_url: 'https://www.audible.com/pd/The-Emotional-Lives-of-Animals-Audiobook/B002V8KQAI'
  },
  {
    title: 'How Dogs Love Us: A Neuroscientist and His Adopted Dog Decode the Canine Brain',
    author: 'Gregory Berns, MD, PhD',
    publisher: 'Mariner Books',
    year: 2013,
    pages: 256,
    isbn: '978-0544114678',
    price_range: '$14-17',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Dog Psychology & Cognition',
    description: "Neuroscientist Gregory Berns trained dogs to voluntarily enter an fMRI machine while awake and unrestrained - a groundbreaking achievement. The resulting brain scans reveal how dogs process human faces, voices, and emotions. Fascinating journey into the neuroscience of the human-dog bond. Combines hard science with personal narrative about Bern's relationship with his own dogs.",
    why_you_need_it: 'Scientific proof that dogs experience genuine emotions and attachment. Powerful tool for client education.',
    best_for: 'Understanding the science of bonding, explaining training methods to clients, inspiration',
    purchase_url: 'https://www.amazon.com/How-Dogs-Love-Us-Neuroscientist/dp/0544114671',
    audible_url: 'https://www.audible.com/pd/How-Dogs-Love-Us-Audiobook/B00FGDUYQC'
  },
  {
    title: 'Dog Is Love: Why and How Your Dog Loves You',
    author: 'Clive Wynne, PhD',
    publisher: 'Mariner Books',
    year: 2019,
    pages: 290,
    isbn: '978-1328543844',
    price_range: '$15-18',
    format: 'Hardcover, Kindle, Audiobook',
    category: 'Dog Psychology & Cognition',
    description: "Canine behavioral scientist Clive Wynne argues that the key to understanding dogs isn't intelligence or theory of mind - it's their extraordinary capacity for love and forming attachments. Reviews decades of research on dog cognition, domestication, and behavior. Wynne makes a compelling case that dogs' defining trait is hypersociability and emotional connection to humans. Challenges some popular assumptions about dog intelligence while celebrating their unique gifts.",
    why_you_need_it: "Reframes how we understand dog behavior. Love and attachment explain more than 'dominance' ever could.",
    best_for: 'Understanding separation anxiety, attachment behavior, building trust with reactive dogs',
    purchase_url: 'https://www.amazon.com/Dog-Love-Why-How-Your/dp/1328543846',
    audible_url: 'https://www.audible.com/pd/Dog-Is-Love-Audiobook/0358159369'
  },
  {
    title: 'Being a Dog: Following the Dog Into a World of Smell',
    author: 'Alexandra Horowitz, PhD',
    publisher: 'Scribner',
    year: 2016,
    pages: 336,
    isbn: '978-1476795997',
    price_range: '$16-19',
    format: 'Hardcover, Paperback, Kindle, Audiobook',
    category: 'Dog Psychology & Cognition',
    description: "Horowitz's follow-up to Inside of a Dog focuses entirely on olfaction - the sense of smell. Explores: how dogs use smell to navigate the world, scent detection abilities, what dogs can learn from urine and feces, how smell shapes their perception of time and memory. Includes interviews with scent detection experts, perfumers, and working dog trainers. Mind-expanding perspective on why walks are so important.",
    why_you_need_it: 'Transforms how you think about walks and enrichment. Essential for urban dogs who navigate by nose.',
    best_for: 'Enrichment strategies, understanding marking behavior, decompression walks',
    purchase_url: 'https://www.amazon.com/Being-Dog-Following-Into-World/dp/1476795991',
    audible_url: 'https://www.audible.com/pd/Being-a-Dog-Audiobook/B01LWUKEIK'
  },
  {
    title: 'Clinical Behavioral Medicine for Small Animals',
    author: 'Karen L. Overall, MA, VMD, PhD, DACVB',
    publisher: 'Mosby',
    year: 1997,
    pages: 544,
    isbn: '978-0801679988',
    price_range: '$50-80 (used)',
    format: 'Hardcover',
    category: 'Dog Psychology & Cognition',
    description: "Comprehensive veterinary textbook on behavioral medicine. Overall is a board-certified veterinary behaviorist and this is THE reference text in the field. Covers: anxiety disorders, compulsive behaviors, aggression, fear-based problems, psychopharmacology, neurochemistry of behavior, and detailed treatment protocols. Very technical and dense, but gold standard for serious behavior work. Includes detailed questionnaires and assessment tools.",
    why_you_need_it: 'When to refer to a vet behaviorist, understanding behavior modification protocols, recognizing medical issues.',
    best_for: 'Serious behavior cases, medical differentials, professional development',
    purchase_url: 'https://www.amazon.com/Clinical-Behavioral-Medicine-Small-Animals/dp/0801679982',
    audible_url: nil
  },
  {
    title: 'Canine Behavior: Insights and Answers (2nd Edition)',
    author: 'Bonnie V. Beaver, DVM, MS, DACVB',
    publisher: 'Saunders',
    year: 2009,
    pages: 392,
    isbn: '978-1416056874',
    price_range: '$60-90',
    format: 'Hardcover, Kindle',
    category: 'Dog Psychology & Cognition',
    description: "Question-and-answer format veterinary behavior reference. Dr. Beaver, a pioneer in veterinary behavior medicine, addresses hundreds of real-world behavior questions organized by topic. Covers: normal development, breed-specific behaviors, geriatric changes, problem behaviors, and treatment approaches. More accessible than Overall's textbook but still scientifically rigorous. Excellent quick reference.",
    why_you_need_it: 'Quick answers to specific behavior questions, understanding breed tendencies, age-related changes.',
    best_for: 'Reference tool, client questions, professional library',
    purchase_url: 'https://www.amazon.com/Canine-Behavior-Insights-Answers-2e/dp/1416056874',
    audible_url: nil
  },

  # CATEGORY 3: HUMAN-DOG BOND & RELATIONSHIP PSYCHOLOGY
  {
    title: 'Made for Each Other: The Biology of the Human-Animal Bond',
    author: 'Meg Daley Olmert',
    publisher: 'Da Capo Press',
    year: 2009,
    pages: 352,
    isbn: '978-0306817335',
    price_range: '$16-20',
    format: 'Paperback, Kindle',
    category: 'Human-Dog Bond & Relationship Psychology',
    description: 'Explores the biological basis of the human-animal bond through the lens of oxytocin, the "bonding hormone." Olmert explains how humans and dogs co-evolved, how touch and eye contact trigger oxytocin release in both species, and why this bond is physiologically beneficial. Covers research on therapy animals, health benefits of pet ownership, and evolutionary theories of domestication. Accessible science writing that validates what dog lovers instinctively know.',
    why_you_need_it: 'Explains WHY dogs are therapeutic. Essential context for emotional support and therapy dog work.',
    best_for: 'Client education, understanding attachment, bonding exercises',
    purchase_url: 'https://www.amazon.com/Made-Each-Other-Biology-Human-Animal/dp/0306817330',
    audible_url: nil
  },
  {
    title: 'The Forever Dog: Surprising New Science to Help Your Canine Companion Live Younger, Healthier, and Longer',
    author: 'Rodney Habib & Dr. Karen Shaw Becker',
    publisher: 'HarperOne',
    year: 2021,
    pages: 432,
    isbn: '978-0063038226',
    price_range: '$18-25',
    format: 'Hardcover, Kindle, Audiobook',
    category: 'Human-Dog Bond & Relationship Psychology',
    description: 'Comprehensive guide to dog longevity covering nutrition, exercise, stress reduction, environmental factors, and preventive care. Habib (pet health advocate) and Becker (integrative veterinarian) review the latest research on what makes dogs live longer, healthier lives. Challenges conventional thinking about dog food, exercise, and healthcare. Emphasizes the role of chronic stress and inflammation in aging.',
    why_you_need_it: 'Urban dogs face unique health stressors. This book provides holistic wellness framework for dog walkers.',
    best_for: 'Enrichment planning, stress reduction, client education on wellness',
    purchase_url: 'https://www.amazon.com/Forever-Dog-Surprising-Science-Companion/dp/0063038226',
    audible_url: 'https://www.audible.com/pd/The-Forever-Dog-Audiobook/0063038242'
  },
  {
    title: 'In Defense of Dogs: Why Dogs Need Our Understanding',
    author: 'John Bradshaw, PhD',
    publisher: 'Penguin Books',
    year: 2011,
    pages: 368,
    isbn: '978-0143119876',
    price_range: '$15-18',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Human-Dog Bond & Relationship Psychology',
    description: "Dog behavior expert Bradshaw argues that dogs are unique animals who should be understood on their own terms, not as failed wolves. Critically examines dominance theory and pack leadership myths. Covers: dog domestication history, sensory capabilities, learning abilities, and breed differences. Emphasizes dogs' adaptability and desire to cooperate with humans. Essential reading for anyone still influenced by outdated training philosophies.",
    why_you_need_it: 'Debunks harmful myths still prevalent among dog owners. Provides scientific ammunition for client education.',
    best_for: 'Countering dominance theory, explaining modern training to skeptical clients',
    purchase_url: 'https://www.amazon.com/Defense-Dogs-Dogs-Need-Understanding/dp/0143119877',
    audible_url: 'https://www.audible.com/pd/In-Defense-of-Dogs-Audiobook/B004EXTPDC'
  },
  {
    title: 'Treating Separation Anxiety in Dogs',
    author: 'Malena DeMartini-Price, CTC',
    publisher: 'Dogwise Publishing',
    year: 2014,
    pages: 176,
    isbn: '978-1617811401',
    price_range: '$20-25',
    format: 'Paperback, Kindle',
    category: 'Human-Dog Bond & Relationship Psychology',
    description: "DeMartini-Price is THE separation anxiety specialist. This book provides a systematic protocol for treating true separation anxiety (not just isolation distress). Covers: assessment criteria, baseline establishment, gradual desensitization plans, criteria for advancing, troubleshooting setbacks, and case studies. Includes detailed training plans and video analysis techniques. Essential for professional trainers working with SA cases.",
    why_you_need_it: 'Separation anxiety is epidemic in urban dogs. This is the gold-standard protocol.',
    best_for: 'SA treatment plans, remote training skills, complex behavior cases',
    purchase_url: 'https://www.amazon.com/Treating-Separation-Anxiety-Dogs/dp/1617811408',
    audible_url: nil
  },
  {
    title: 'Fired Up, Frantic, and Freaked Out: Training the Crazy Dog from Over Aroused to Under Control',
    author: 'Laura VanArendonk Baugh, CPDT-KA, KPACTP',
    publisher: 'Dogwise Publishing',
    year: 2013,
    pages: 144,
    isbn: '978-1617811128',
    price_range: '$18-22',
    format: 'Paperback, Kindle',
    category: 'Human-Dog Bond & Relationship Psychology',
    description: "Practical guide to working with high-arousal, reactive, and overstimulated dogs. VanArendonk Baugh explains arousal levels, triggers, thresholds, and how to bring dogs down from emotional highs. Covers: impulse control exercises, developing calmness, teaching emotional regulation, and working with fearful or aggressive dogs. Extremely relevant for urban environments where triggers are everywhere. Clear protocols and training games included.",
    why_you_need_it: 'Most urban dogs struggle with arousal and overstimulation. Essential toolkit for NYC dog walkers.',
    best_for: 'Reactivity, impulse control, urban environment training',
    purchase_url: 'https://www.amazon.com/Fired-Up-Frantic-Freaked-Out/dp/1617811122',
    audible_url: nil
  },

  # CATEGORY 4: PACK DYNAMICS & CANINE COMMUNICATION
  {
    title: 'On Talking Terms with Dogs: Calming Signals (2nd Edition)',
    author: 'Turid Rugaas',
    publisher: 'Dogwise Publishing',
    year: 2006,
    pages: 96,
    isbn: '978-1929242361',
    price_range: '$15-18',
    format: 'Paperback, Kindle',
    category: 'Pack Dynamics & Canine Communication',
    description: "Norwegian dog trainer Rugaas identified 30+ 'calming signals' - subtle body language cues dogs use to communicate stress, avoid conflict, and calm themselves or others. Short, illustrated guide covering: lip licking, yawning, turning away, play bows, and more. Essential for reading dog body language accurately. Teaches handlers how to use calming signals to communicate with dogs in their own language.",
    why_you_need_it: 'Reading stress signals prevents bites and improves training timing. Critical safety skill for dog walkers.',
    best_for: 'Body language fluency, dog-dog interactions, stress detection',
    purchase_url: 'https://www.amazon.com/Talking-Terms-Dogs-Calming-Signals/dp/1929242360',
    audible_url: nil
  },
  {
    title: 'Canine Body Language: A Photographic Guide to the Native Language of Dogs',
    author: 'Brenda Aloff',
    publisher: 'Dogwise Publishing',
    year: 2005,
    pages: 384,
    isbn: '978-1929242351',
    price_range: '$35-45',
    format: 'Paperback',
    category: 'Pack Dynamics & Canine Communication',
    description: "Comprehensive visual guide to reading dog body language. Hundreds of photos with detailed analysis of: facial expressions, ear positions, tail carriage, body posture, stress signals, appeasement gestures, and aggressive displays. Aloff breaks down complex interactions moment-by-moment. Essential reference for anyone doing behavior assessments or working with multiple dogs. Large format book with high-quality photographs.",
    why_you_need_it: 'Visual literacy in dog body language is a professional requirement. This is the definitive photo guide.',
    best_for: 'Body language mastery, play assessments, aggression recognition',
    purchase_url: 'https://www.amazon.com/Canine-Body-Language-Photographic-Interpreting/dp/1929242352',
    audible_url: nil
  },
  {
    title: 'Social, Civil, & Savvy: Training & Socializing Puppies to Become the Best Possible Dogs',
    author: 'Laura VanArendonk Baugh, CPDT-KA, KPACTP',
    publisher: 'Dogwise Publishing',
    year: 2020,
    pages: 224,
    isbn: '978-1617812163',
    price_range: '$20-25',
    format: 'Paperback, Kindle',
    category: 'Pack Dynamics & Canine Communication',
    description: "Modern, comprehensive puppy socialization guide. Goes beyond 'expose puppies to everything' to teach HOW to socialize properly - creating positive associations, respecting puppy choice, avoiding flooding and sensitization. Covers: critical periods, appropriate play, handling exercises, environmental exposure, and problem prevention. Emphasizes building confidence and emotional resilience. Particularly valuable for urban puppy raising.",
    why_you_need_it: 'Proper socialization prevents behavior problems. Essential for puppy clients and group classes.',
    best_for: 'Puppy socialization protocols, client education, group class curriculum',
    purchase_url: 'https://www.amazon.com/Social-Civil-Savvy-Training-Socializing/dp/1617812161',
    audible_url: nil
  },
  {
    title: 'Successful Dog Adoption',
    author: 'Sue Sternberg',
    publisher: 'Howell Book House',
    year: 2003,
    pages: 288,
    isbn: '978-0764526527',
    price_range: '$18-25',
    format: 'Paperback',
    category: 'Pack Dynamics & Canine Communication',
    description: "Guide to evaluating shelter dogs for adoption and matching them with appropriate homes. Sternberg, a shelter consultant, developed widely-used temperament testing protocols. Covers: assessing arousal levels, resource guarding tests, dog-dog interactions, child safety, bite risk factors, and post-adoption training. Includes detailed assessment forms and criteria. Critical reading for anyone working with rescue dogs or conducting behavior evaluations.",
    why_you_need_it: 'Most urban dogs are rescues. Understanding their history and behavior helps create effective training plans.',
    best_for: 'Rescue dog assessment, safety evaluation, matching dogs to homes',
    purchase_url: 'https://www.amazon.com/Successful-Dog-Adoption-Sue-Sternberg/dp/0764526529',
    audible_url: nil
  },

  # CATEGORY 5: URBAN & SPECIALIZED TRAINING
  {
    title: 'Plenty in Life Is Free: Reflections on Dogs, Training, and Finding Grace',
    author: 'Kathy Sdao, MA, ACAAB',
    publisher: 'Dogwise Publishing',
    year: 2012,
    pages: 192,
    isbn: '978-1617810398',
    price_range: '$18-22',
    format: 'Paperback, Kindle',
    category: 'Urban & Specialized Training',
    description: "Challenges the traditional 'Nothing in Life is Free' (NILIF) training protocol. Sdao, a marine mammal trainer turned dog trainer, argues for relationship-based training that emphasizes generosity, trust, and freely given rewards alongside earned ones. Blends training philosophy, personal narrative, and practical protocols. Thoughtful examination of power dynamics in training relationships. Includes specific training games and exercises.",
    why_you_need_it: 'Reframes training relationship from transactional to relational. Particularly important for anxious or traumatized dogs.',
    best_for: 'Building trust, working with fearful dogs, relationship-building exercises',
    purchase_url: 'https://www.amazon.com/Plenty-Life-Free-Reflections-Training/dp/1617810398',
    audible_url: nil
  },
  {
    title: 'Control Unleashed: Creating a Focused and Confident Dog',
    author: 'Leslie McDevitt, MLA, CDBC, CPDT-KA',
    publisher: 'Clean Run Productions',
    year: 2007,
    pages: 249,
    isbn: '978-1892694201',
    price_range: '$25-30',
    format: 'Paperback',
    category: 'Urban & Specialized Training',
    description: "Revolutionary program for teaching dogs to relax, focus, and work despite distractions and stressors. Originally developed for reactive agility dogs but widely applicable. Covers: default behaviors, Look at That (LAT) game, parallel games, relaxation protocols, and building focus in high-distraction environments. McDevitt integrates behavioral science, body awareness, and mindfulness concepts. Essential toolkit for urban dog training.",
    why_you_need_it: 'Urban dogs need impulse control and focus despite constant stimulation. CU games are industry standard.',
    best_for: 'Reactivity, focus building, impulse control, urban environment success',
    purchase_url: 'https://www.amazon.com/Control-Unleashed-Creating-Focused-Confident/dp/1892694204',
    audible_url: nil
  },
  {
    title: 'Control Unleashed: Reactive to Relaxed',
    author: 'Leslie McDevitt, MLA, CDBC, CPDT-KA',
    publisher: 'Clean Run Productions',
    year: 2016,
    pages: 240,
    isbn: '978-1892694669',
    price_range: '$28-35',
    format: 'Paperback',
    category: 'Urban & Specialized Training',
    description: "Follow-up to Control Unleashed focusing specifically on reactivity. Expands on LAT (Look at That) game, introduces Engage-Disengage protocol, Pattern Games, and comprehensive reactivity rehabilitation program. Includes detailed case studies, troubleshooting sections, and integration with other training approaches. More accessible than original CU and directly applicable to leash reactivity, which is epidemic in urban environments.",
    why_you_need_it: 'Most urban dogs have some reactivity. This is a complete, proven protocol for addressing it.',
    best_for: 'Leash reactivity, trigger stacking management, urban walking success',
    purchase_url: 'https://www.amazon.com/Control-Unleashed-Reactive-Relaxed-Program/dp/1892694662',
    audible_url: nil
  },

  # CATEGORY 6: ENRICHMENT & WELLNESS
  {
    title: 'Canine Enrichment for the Real World: Making It a Part of Your Dog\'s Daily Life',
    author: 'Allie Bender, CDBC & Emily Strong, CDBC',
    publisher: 'Dogwise Publishing',
    year: 2019,
    pages: 192,
    isbn: '978-1617812613',
    price_range: '$20-25',
    format: 'Paperback, Kindle',
    category: 'Enrichment & Wellness',
    description: "Practical, comprehensive guide to enrichment covering: physical, cognitive, sensory, social, and novelty-based enrichment. Bender and Strong (both certified dog behavior consultants) provide hundreds of enrichment ideas organized by category, budget, and effort level. Explains WHY enrichment matters for behavior and wellness. Includes troubleshooting sections and enrichment plans for specific behavior issues. Essential resource for creating fulfilling lives for urban dogs.",
    why_you_need_it: 'Enrichment prevents behavior problems and improves quality of life. Must-have for professional dog walkers.',
    best_for: 'Daily enrichment ideas, behavior problem prevention, client education',
    purchase_url: 'https://www.amazon.com/Canine-Enrichment-Real-World-Making/dp/1617812617',
    audible_url: nil
  },
  {
    title: 'Wag: The Science of Making Your Dog Happy',
    author: 'Zazie Todd, PhD',
    publisher: 'Greystone Books',
    year: 2020,
    pages: 256,
    isbn: '978-1771647915',
    price_range: '$17-22',
    format: 'Hardcover, Kindle, Audiobook',
    category: 'Enrichment & Wellness',
    description: "Science-backed guide to dog happiness and wellbeing. Todd (animal behavior scientist and psychology PhD) reviews research on: what dogs need to thrive, how they experience the world, training methods and welfare, play, socialization, exercise, and end-of-life care. Accessible writing that translates research into practical tips. Emphasizes positive reinforcement and understanding dogs' emotional needs. Holistic approach to dog care.",
    why_you_need_it: 'Happiness and welfare should guide all training decisions. This book provides the evidence base.',
    best_for: 'Holistic wellness approach, client education, ethical training framework',
    purchase_url: 'https://www.amazon.com/Science-Making-Your-Dog-Happy/dp/1771647914',
    audible_url: 'https://www.audible.com/pd/The-Science-of-Making-Your-Dog-Happy-Audiobook/B0CG4JSGYZ'
  },

  # CATEGORY 7: EVOLUTION & DOMESTICATION
  {
    title: 'The Genius of Dogs: How Dogs Are Smarter Than You Think',
    author: 'Brian Hare, PhD & Vanessa Woods',
    publisher: 'Dutton',
    year: 2013,
    pages: 336,
    isbn: '978-0142180846',
    price_range: '$16-20',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Evolution & Domestication',
    description: "Evolutionary anthropologist Brian Hare founded Dognition (citizen science project studying dog cognition). This book summarizes decades of research on dog intelligence, particularly their unique ability to read human social cues. Covers: domestication theories, breed differences in cognition, problem-solving abilities, and communication skills. Argues that dogs' social intelligence is their genius - they're specially adapted to understand humans. Engaging storytelling backed by rigorous science.",
    why_you_need_it: 'Understanding what dogs are good at (and what they struggle with) shapes realistic training goals.',
    best_for: 'Breed tendencies, cognitive enrichment, understanding limitations',
    purchase_url: 'https://www.amazon.com/Genius-Dogs-Smarter-Than-Think/dp/0142180847',
    audible_url: 'https://www.audible.com/pd/The-Genius-of-Dogs-Audiobook/B009LRWHXO'
  },
  {
    title: 'Dog Sense: How the New Science of Dog Behavior Can Make You a Better Friend to Your Pet',
    author: 'John Bradshaw, PhD',
    publisher: 'Basic Books',
    year: 2011,
    pages: 336,
    isbn: '978-0465030644',
    price_range: '$15-18',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Evolution & Domestication',
    description: "Anthrozoologist Bradshaw examines the latest science on dog behavior, senses, communication, and cognition. Focuses on understanding dogs as a unique species shaped by domestication, not as wolves or furry humans. Covers: sensory world of dogs, how they learn, social behavior, breed differences, and practical training applications. Critical of outdated dominance-based training. Accessible science writing that changes how you see your dog.",
    why_you_need_it: 'Science-based understanding of dog behavior informs better training and management decisions.',
    best_for: 'Foundational understanding, debunking myths, force-free training rationale',
    purchase_url: 'https://www.amazon.com/Dog-Sense-Science-Behavior-Better/dp/0465030645',
    audible_url: 'https://www.audible.com/pd/Dog-Sense-Audiobook/B005QSVS92'
  },
  {
    title: 'Dog: A Natural History',
    author: 'Adam Miklósi, PhD',
    publisher: 'Princeton University Press',
    year: 2018,
    pages: 224,
    isbn: '978-0691176277',
    price_range: '$22-28',
    format: 'Hardcover, Kindle',
    category: 'Evolution & Domestication',
    description: "Beautifully illustrated comprehensive natural history of domestic dogs. Miklósi, a leading dog cognition researcher, covers: evolutionary origins, domestication process, anatomy, behavior, communication, cognition, working dogs, and human-dog relationships. Combines scientific depth with stunning photography and illustrations. More textbook-like than narrative, but authoritative and comprehensive. Excellent reference book for serious students of dogs.",
    why_you_need_it: 'Comprehensive reference on dog biology, evolution, and behavior in one gorgeous volume.',
    best_for: 'Professional library, reference tool, evolutionary context',
    purchase_url: 'https://www.amazon.com/Dog-Natural-History-Adam-Mikl%C3%B3si/dp/0691176272',
    audible_url: nil
  },

  # CATEGORY 8: AGGRESSION & PROBLEM BEHAVIORS
  {
    title: 'Aggression in Dogs: Practical Management, Prevention, and Behaviour Modification',
    author: 'Brenda Aloff',
    publisher: 'Dogwise Publishing',
    year: 2002,
    pages: 480,
    isbn: '978-1929242351',
    price_range: '$40-55',
    format: 'Paperback',
    category: 'Aggression & Problem Behaviors',
    description: "Comprehensive professional reference on canine aggression. Aloff covers: types of aggression, assessment protocols, safety management, behavior modification techniques, body language, and case studies. Includes detailed photos illustrating aggressive displays and subtle warning signs. Practical management strategies and training plans. Large format book. Essential for anyone working with aggressive dogs or conducting behavior consultations.",
    why_you_need_it: 'Aggression is the #1 reason dogs are surrendered. Understanding it is critical for safety and successful interventions.',
    best_for: 'Aggression cases, safety protocols, professional development',
    purchase_url: 'https://www.amazon.com/Aggression-Dogs-Practical-Management-Prevention/dp/1929242352',
    audible_url: nil
  },
  {
    title: 'Mine! A Practical Guide to Resource Guarding in Dogs',
    author: 'Jean Donaldson',
    publisher: 'Kinship Communications',
    year: 2002,
    pages: 96,
    isbn: '978-0970562944',
    price_range: '$18-25',
    format: 'Paperback',
    category: 'Aggression & Problem Behaviors',
    description: "Focused, practical guide to assessing and treating resource guarding behavior. Donaldson presents clear protocols for: evaluating severity, safety management, desensitization and counterconditioning plans, working with object guarders vs. space guarders, and prevention in puppies. Step-by-step training plans with clear criteria for progress. Short but packed with essential information. Gold standard protocol for RG.",
    why_you_need_it: 'Resource guarding is common and dangerous if mishandled. This protocol works and keeps everyone safe.',
    best_for: 'Resource guarding cases, food bowl aggression, safety protocols',
    purchase_url: 'https://www.amazon.com/Mine-Practical-Guide-Resource-Guarding/dp/0970562942',
    audible_url: nil
  },

  # CATEGORY 9: PROFESSIONAL DEVELOPMENT
  {
    title: 'The Midnight Dog Walkers: Positive Training and Practical Advice for Living with Reactive and Aggressive Dogs',
    author: 'Annie Phenix, CPDT-KA',
    publisher: 'Dogwise Publishing',
    year: 2016,
    pages: 208,
    isbn: '978-1617812071',
    price_range: '$18-22',
    format: 'Paperback, Kindle',
    category: 'Professional Development',
    description: "Written for owners AND trainers of reactive/aggressive dogs. Phenix shares her experience living with and rehabilitating reactive dogs, including practical management strategies for urban environments. Covers: safety protocols, training techniques, emotional toll on handlers, building support networks, and knowing when to euthanize. Compassionate, realistic, and practical. Essential reading for understanding what clients with difficult dogs experience daily.",
    why_you_need_it: 'Empathy for clients with reactive dogs improves training outcomes. This book builds that empathy.',
    best_for: 'Client perspective, management strategies, emotional support skills',
    purchase_url: 'https://www.amazon.com/Midnight-Dog-Walkers-Positive-Training/dp/1617812072',
    audible_url: nil
  },
  {
    title: 'Dog Training Professional: The Complete Guide to Starting Your Career',
    author: 'Lisa Lyle Waggoner',
    publisher: 'Dogwise Publishing',
    year: 2018,
    pages: 256,
    isbn: '978-1617812866',
    price_range: '$22-28',
    format: 'Paperback, Kindle',
    category: 'Professional Development',
    description: "Comprehensive business guide for professional dog trainers. Covers: deciding if training is right for you, choosing certifications, business structures, pricing, marketing, contracts, liability insurance, client communication, continuing education, and work-life balance. Waggoner (founder of Cold Nose College) combines industry wisdom with practical templates and checklists. Essential for anyone considering professional dog training.",
    why_you_need_it: 'Starting a dog training business requires more than training skills. This book covers the business essentials.',
    best_for: 'Career planning, business setup, professional development roadmap',
    purchase_url: 'https://www.amazon.com/Dog-Training-Professional-Complete-Starting/dp/1617812862',
    audible_url: nil
  },

  # CATEGORY 10: REFERENCE & QUICK GUIDES
  {
    title: 'The Toolbox for Building a Great Family Dog',
    author: 'Terry Ryan',
    publisher: 'Dogwise Publishing',
    year: 2012,
    pages: 144,
    isbn: '978-1617811142',
    price_range: '$18-22',
    format: 'Paperback, Kindle',
    category: 'Reference & Quick Guides',
    description: "Practical training manual organized by exercises rather than problems. Ryan (legendary dog trainer and founder of Legacy Canine) presents clear, step-by-step protocols for: attention, recall, loose leash walking, stay, settle, and more. Each 'tool' includes training steps, troubleshooting, and applications. Spiral-bound for easy reference during training sessions. Perfect for new trainers or experienced ones who need quick protocol references.",
    why_you_need_it: 'Having clear, proven protocols at your fingertips makes training sessions more productive.',
    best_for: 'Training protocols, client handouts, group class curriculum',
    purchase_url: 'https://www.amazon.com/Toolbox-Building-Great-Family-Dog/dp/1617811149',
    audible_url: nil
  },
  {
    title: 'The Power of Positive Dog Training (2nd Edition)',
    author: 'Pat Miller, CBCC-KA, CPDT-KA',
    publisher: 'Howell Book House',
    year: 2008,
    pages: 352,
    isbn: '978-0470241745',
    price_range: '$18-23',
    format: 'Paperback, Kindle',
    category: 'Reference & Quick Guides',
    description: "Comprehensive positive reinforcement training guide for pet dog owners. Miller, a respected trainer and writer, covers: basic obedience, problem prevention, common behavior issues, and advanced training. Clear instructions, troubleshooting tips, and week-by-week training plans. Excellent gift for new dog owners or reference for trainers working with clients. Updated second edition includes clicker training integration and modern protocols.",
    why_you_need_it: 'Solid foundation in positive training methods. Great recommendation for clients who want to learn more.',
    best_for: 'Client recommendations, basic training protocols, owner education',
    purchase_url: 'https://www.amazon.com/Power-Positive-Dog-Training/dp/0470241748',
    audible_url: nil
  },
  {
    title: 'Oh Behave! Dogs from Pavlov to Premack to Pinker',
    author: 'Jean Donaldson',
    publisher: 'Dogwise Publishing',
    year: 2008,
    pages: 192,
    isbn: '978-1929242863',
    price_range: '$20-25',
    format: 'Paperback',
    category: 'Reference & Quick Guides',
    description: "Collection of Donaldson's best essays on dog behavior and training. Covers: learning theory deep dives, training philosophy, common myths, assessment techniques, and ethical considerations. Written in Donaldson's characteristically sharp, witty style. More advanced than The Culture Clash - assumes reader has foundational knowledge. Excellent for deepening understanding and critical thinking about training.",
    why_you_need_it: 'Sharpens critical thinking about training methods and challenges assumptions. Professional development reading.',
    best_for: 'Advanced learning theory, training philosophy, critical thinking',
    purchase_url: 'https://www.amazon.com/Oh-Behave-Dogs-Pavlov-Premack/dp/1929242867',
    audible_url: nil
  },

  # CATEGORY 11: SPECIALIZED TOPICS
  {
    title: 'Do Over Dogs: Give Your Dog a Second Chance for a First Class Life',
    author: 'Pat Miller, CBCC-KA, CPDT-KA',
    publisher: 'Dogwise Publishing',
    year: 2010,
    pages: 288,
    isbn: '978-1929242894',
    price_range: '$20-25',
    format: 'Paperback',
    category: 'Specialized Topics',
    description: "Comprehensive guide to rehabilitating rescue dogs with behavior challenges. Miller addresses: fear, aggression, separation anxiety, house training, resource guarding, and more. Realistic about challenges while remaining optimistic about outcomes. Includes assessment tools, training protocols, and knowing when to seek professional help or consider euthanasia. Particularly relevant for urban environments where most dogs are rescues.",
    why_you_need_it: 'Most urban dogs are rescues with unknown histories. This book provides rehabilitation roadmap.',
    best_for: 'Rescue dog rehabilitation, behavior modification, realistic expectations',
    purchase_url: 'https://www.amazon.com/Over-Dogs-Second-Chance-First/dp/1929242891',
    audible_url: nil
  },
  {
    title: 'Brenda Aloff\'s Fundamentals: Foundation Training for Every Dog',
    author: 'Brenda Aloff',
    publisher: 'Dogwise Publishing',
    year: 2011,
    pages: 224,
    isbn: '978-1617810183',
    price_range: '$22-28',
    format: 'Paperback',
    category: 'Specialized Topics',
    description: "Step-by-step foundational training program. Aloff presents systematic approach to: attention, impulse control, body awareness, handling tolerance, and basic obedience. Emphasizes building solid foundations before advanced training. Clear instructions with photos. Particularly strong on body awareness exercises and shaping calm behavior. Excellent framework for group classes or private training programs.",
    why_you_need_it: 'Many dogs skip foundation skills. This systematic program builds the missing pieces.',
    best_for: 'Foundation training, group class curriculum, systematic skill building',
    purchase_url: 'https://www.amazon.com/Brenda-Aloffs-Fundamentals-Foundation-Training/dp/1617810185',
    audible_url: nil
  },
  {
    title: 'Behavior Problems of the Dog and Cat (3rd Edition)',
    author: 'Gary Landsberg, Wayne Hunthausen, Lowell Ackerman',
    publisher: 'Saunders',
    year: 2012,
    pages: 592,
    isbn: '978-0702042850',
    price_range: '$90-130',
    format: 'Hardcover, Kindle',
    category: 'Specialized Topics',
    description: "Veterinary textbook on behavioral medicine for both dogs and cats. Three veterinary behaviorists provide comprehensive coverage of: normal behavior, problem behavior diagnosis and treatment, psychopharmacology, medical differentials, and specific behavior disorders. Very technical and detailed. Includes treatment protocols, medication guidelines, and case studies. Professional reference for complex cases requiring veterinary involvement.",
    why_you_need_it: 'Understanding when behavior problems have medical components. When to refer to vet behaviorist.',
    best_for: 'Medical differentials, psychopharmacology basics, complex cases',
    purchase_url: 'https://www.amazon.com/Behavior-Problems-Dog-Cat-3e/dp/0702042854',
    audible_url: nil
  },

  # CATEGORY 12: TRAINING SPECIFIC SKILLS
  {
    title: 'When Pigs Fly! Training Success with Impossible Dogs',
    author: 'Jane Killion',
    publisher: 'Dogwise Publishing',
    year: 2007,
    pages: 176,
    isbn: '978-1929242412',
    price_range: '$18-22',
    format: 'Paperback',
    category: 'Training Specific Skills',
    description: "Training guide specifically for 'impossible' dogs - independent breeds, low-motivation dogs, and dogs who don't respond to traditional training. Killion (Bull Terrier enthusiast) explains how to motivate the unmotivated, train dogs with low food drive, and succeed with breeds that aren't biddable. Covers: building drive, creative reinforcement strategies, and modifying training approaches for different personalities. Encouraging and practical.",
    why_you_need_it: 'Not every dog is a Golden Retriever. This book helps train dogs who march to their own drum.',
    best_for: 'Independent breeds, low-motivation dogs, creative training approaches',
    purchase_url: 'https://www.amazon.com/When-Pigs-Fly-Training-Impossible/dp/1929242417',
    audible_url: nil
  },
  {
    title: 'Click to Calm: Healing the Aggressive Dog',
    author: 'Emma Parsons',
    publisher: 'Sunshine Books',
    year: 2004,
    pages: 224,
    isbn: '978-1890948207',
    price_range: '$25-30',
    format: 'Paperback',
    category: 'Training Specific Skills',
    description: "Clicker-based protocol for rehabilitating aggressive and reactive dogs. Parsons developed these techniques while working with her own dog-aggressive dog. Detailed training plans for: desensitization, building calm responses to triggers, impulse control, and off-leash reliability. Includes extensive troubleshooting sections and case studies. Foundation for many modern reactivity protocols. Clear instructions with photos.",
    why_you_need_it: 'Systematic clicker-based protocol for reactivity that actually works. Foundation for modern approaches.',
    best_for: 'Dog-dog aggression, reactivity rehabilitation, clicker training',
    purchase_url: 'https://www.amazon.com/Click-Calm-Healing-Aggressive-Dog/dp/1890948209',
    audible_url: nil
  },
  {
    title: 'Reaching the Animal Mind: Clicker Training and What It Teaches Us About All Animals',
    author: 'Karen Pryor',
    publisher: 'Scribner',
    year: 2009,
    pages: 320,
    isbn: '978-0743297776',
    price_range: '$16-20',
    format: 'Hardcover, Paperback, Kindle, Audiobook',
    category: 'Training Specific Skills',
    description: "Pryor's exploration of clicker training across species - from dogs to dolphins to fish to humans. Explains: learning theory principles, shaping complex behaviors, building relationships through training, and how reinforcement-based training creates willing, confident learners. Combines personal stories from Pryor's career with practical training applications. Inspiring and educational. Shows the power and versatility of positive reinforcement.",
    why_you_need_it: 'Understanding cross-species training principles deepens training skills and shows universal nature of learning theory.',
    best_for: 'Clicker training mastery, shaping complex behaviors, training inspiration',
    purchase_url: 'https://www.amazon.com/Reaching-Animal-Mind-Clicker-Training/dp/0743297776',
    audible_url: 'https://www.audible.com/pd/Reaching-the-Animal-Mind-Audiobook/B002V8KPVG'
  },

  # CATEGORY 13: CRITICAL THINKING & SCIENCE
  {
    title: 'Canine Confidential: Why Dogs Do What They Do',
    author: 'Marc Bekoff, PhD',
    publisher: 'University of Chicago Press',
    year: 2018,
    pages: 256,
    isbn: '978-0226433240',
    price_range: '$16-20',
    format: 'Hardcover, Paperback, Kindle, Audiobook',
    category: 'Critical Thinking & Science',
    description: "Bekoff explores the inner lives of dogs through an ethological lens. Covers: sensory experiences, emotions, play behavior, communication, individuality, and how dogs perceive their world. Emphasizes dogs as sentient beings with complex emotional and cognitive lives. Critical of practices that compromise welfare. Combines scientific rigor with accessible storytelling. Important reading for ethical, empathetic dog training.",
    why_you_need_it: 'Ethical training requires understanding dogs as individuals with emotional lives. Foundation for welfare-focused practice.',
    best_for: 'Ethical framework, understanding dog psychology, welfare considerations',
    purchase_url: 'https://www.amazon.com/Canine-Confidential-Why-Dogs-What/dp/0226433242',
    audible_url: 'https://www.audible.com/pd/Canine-Confidential-Audiobook/B079VWZFZB'
  },
  {
    title: 'The Domestic Dog: Its Evolution, Behavior and Interactions with People (2nd Edition)',
    author: 'James Serpell (Editor)',
    publisher: 'Cambridge University Press',
    year: 2016,
    pages: 385,
    isbn: '978-1107699342',
    price_range: '$45-60',
    format: 'Paperback, Kindle',
    category: 'Critical Thinking & Science',
    description: "Academic edited volume with contributions from leading dog researchers. Covers: domestication, genetics, sensory abilities, social behavior, cognition, human-dog relationships, working dogs, welfare, and problem behaviors. Each chapter written by experts in that area. More textbook than popular science - rigorous, referenced, comprehensive. Essential reference for serious students of dog behavior and training professionals.",
    why_you_need_it: 'Most comprehensive academic overview of dog behavior science. Professional reference for deeper understanding.',
    best_for: 'Academic foundation, research summaries, professional development',
    purchase_url: 'https://www.amazon.com/Domestic-Dog-Evolution-Behavior-Interactions/dp/1107699347',
    audible_url: nil
  },
  {
    title: 'Decoding Your Dog: The Ultimate Experts Explain Common Dog Behaviors and Reveal How to Prevent or Change Unwanted Ones',
    author: 'American College of Veterinary Behaviorists',
    publisher: 'Mariner Books',
    year: 2014,
    pages: 480,
    isbn: '978-0547738390',
    price_range: '$16-20',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Critical Thinking & Science',
    description: "Written by board-certified veterinary behaviorists (the highest credential in animal behavior). Covers: normal development, communication, learning, common behavior problems (aggression, anxiety, compulsive behaviors), and when to seek professional help. Each chapter written by a different DACVB specialist. Scientifically accurate, practical, and comprehensive. Important perspective from the veterinary medical side of behavior.",
    why_you_need_it: 'Understanding veterinary perspective on behavior helps with referrals and recognizing medical issues.',
    best_for: 'Medical behavior issues, when to refer, veterinary perspective',
    purchase_url: 'https://www.amazon.com/Decoding-Your-Dog-Explaining-Behaviors/dp/0547738390',
    audible_url: 'https://www.audible.com/pd/Decoding-Your-Dog-Audiobook/B00IIS32KU'
  },

  # CATEGORY 14: STRESS & ANXIETY
  {
    title: 'Help for Your Fearful Dog: A Step-by-Step Guide to Helping Your Dog Conquer His Fears',
    author: 'Nicole Wilde, CPDT-KA',
    publisher: 'Phantom Publishing',
    year: 2006,
    pages: 256,
    isbn: '978-0966772678',
    price_range: '$20-25',
    format: 'Paperback',
    category: 'Stress & Anxiety',
    description: "Comprehensive guide to working with fearful and anxious dogs. Wilde covers: identifying fear triggers, body language of fear, desensitization and counterconditioning protocols, building confidence, management strategies, and when to consider medication. Practical training plans for common fears: noises, people, dogs, new environments. Compassionate, realistic, and detailed. Essential for working with rescue dogs or any fearful dogs.",
    why_you_need_it: 'Fear-based behaviors are common in urban rescue dogs. This provides clear rehabilitation roadmap.',
    best_for: 'Fearful dogs, noise phobias, building confidence, desensitization protocols',
    purchase_url: 'https://www.amazon.com/Help-Your-Fearful-Dog-Step/dp/0966772679',
    audible_url: nil
  },
  {
    title: 'From Fearful to Fear Free: A Positive Program to Free Your Dog from Anxiety, Fears, and Phobias',
    author: 'Marty Becker, DVM & Mikkel Becker, CPDT-KA, CBCC-KA',
    publisher: 'Health Communications Inc',
    year: 2018,
    pages: 288,
    isbn: '978-0757319655',
    price_range: '$18-24',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Stress & Anxiety',
    description: "Comprehensive program for preventing and treating fear, anxiety, and stress in dogs. Developed by veterinarian Marty Becker (founder of Fear Free veterinary movement) and trainer Mikkel Becker. Covers: recognizing fear signs, preventing fear during critical periods, desensitization protocols, creating fear-free vet visits, medication options, and environmental management. Holistic approach combining training, environmental modification, and medical interventions when needed.",
    why_you_need_it: 'Fear is at the root of many behavior problems. This provides comprehensive treatment framework.',
    best_for: 'Fear-based behaviors, vet visit anxiety, comprehensive treatment planning',
    purchase_url: 'https://www.amazon.com/Fearful-Fear-Free-Positive-Program/dp/0757319653',
    audible_url: 'https://www.audible.com/pd/From-Fearful-to-Fear-Free-Audiobook/B078V43ZFC'
  },
  {
    title: 'Stress in Dogs: Learn How Dogs Show Stress and What You Can Do to Help',
    author: 'Martina Scholz & Clarissa von Reinhardt',
    publisher: 'Dogwise Publishing',
    year: 2007,
    pages: 128,
    isbn: '978-1929242917',
    price_range: '$16-20',
    format: 'Paperback',
    category: 'Stress & Anxiety',
    description: "Short, focused guide on canine stress. German trainers Scholz and von Reinhardt explain: what stress is, physiological stress responses, visible stress signals, chronic stress effects, and stress reduction techniques. Includes photos of stress body language. Emphasizes recognizing subtle stress before it escalates to problem behaviors. Important for understanding trigger stacking in urban environments where dogs face constant stimulation.",
    why_you_need_it: 'Recognizing and managing stress prevents behavior problems. Critical skill for urban dog walkers.',
    best_for: 'Stress signal recognition, trigger stacking management, preventive training',
    purchase_url: 'https://www.amazon.com/Stress-Dogs-Learn-Show-What/dp/1929242918',
    audible_url: nil
  },

  # CATEGORY 15: PLAY & ENRICHMENT
  {
    title: 'Play Together, Stay Together: Happy and Healthy Play Between People and Dogs',
    author: 'Patricia McConnell, PhD & Karen London, PhD',
    publisher: 'McConnell Publishing',
    year: 2008,
    pages: 106,
    isbn: '978-1891767166',
    price_range: '$18-22',
    format: 'Paperback',
    category: 'Play & Enrichment',
    description: "Short guide to healthy, safe play between dogs and people. McConnell and London (both PhDs in animal behavior) explain: different types of play, reading play signals, preventing problems during play, play styles and individual differences, and using play in training. Includes guidelines for play with children. Emphasizes the bonding and enrichment value of appropriate play while preventing arousal issues.",
    why_you_need_it: 'Play is important enrichment but can go wrong. This teaches safe, healthy play guidelines.',
    best_for: 'Play guidelines, client education, appropriate play with kids',
    purchase_url: 'https://www.amazon.com/Play-Together-Stay-Happy-Healthy/dp/1891767166',
    audible_url: nil
  },
  {
    title: 'Dog Smart: Evidence-based Training with The Science Dog',
    author: 'Linda Case',
    publisher: 'Dogwise Publishing',
    year: 2018,
    pages: 304,
    isbn: '978-1617812613',
    price_range: '$22-28',
    format: 'Paperback, Kindle',
    category: 'Play & Enrichment',
    description: "Evidence-based exploration of dog training methods, learning theory, and common myths. Case (dog nutrition and behavior expert) reviews the science behind: positive reinforcement, punishment, dominance theory, pack theory, and various training approaches. Critical analysis of popular training methods and products. Includes practical training applications backed by research. Helps trainers and owners make informed, science-based decisions.",
    why_you_need_it: 'Critical thinking about training methods and claims. Evidence-based decision making.',
    best_for: 'Training philosophy, evidence-based practice, critical thinking',
    purchase_url: 'https://www.amazon.com/Dog-Smart-Evidence-based-Training-Thoughtful/dp/1617812617',
    audible_url: nil
  },

  # CATEGORY 16: PUPPIES & DEVELOPMENT
  {
    title: 'Perfect Puppy in 7 Days: How to Start Your Puppy Off Right',
    author: 'Dr. Sophia Yin, DVM, MS',
    publisher: 'CattleDog Publishing',
    year: 2011,
    pages: 192,
    isbn: '978-0964151871',
    price_range: '$22-28',
    format: 'Paperback',
    category: 'Puppies & Development',
    description: "Week-by-week puppy training program from renowned veterinarian and behaviorist Dr. Sophia Yin. Covers: first week priorities, house training, socialization, basic manners, handling, and preventing common problems. Heavy emphasis on shaping calm behavior and impulse control from day one. Clear instructions with photos and training plans. Designed for busy people who want to do it right. Dr. Yin's untimely death in 2014 was a huge loss for the dog training world.",
    why_you_need_it: 'Early training shapes lifelong behavior. This systematic program sets puppies up for success.',
    best_for: 'Puppy clients, prevention-focused training, new puppy consultations',
    purchase_url: 'https://www.amazon.com/Perfect-Puppy-Days-Start-Right/dp/0964151871',
    audible_url: nil
  },
  {
    title: 'Puppy Start Right: Foundation Training for the Companion Dog',
    author: 'Kenneth Martin, DVM & Debbie Martin, RVT, VTS',
    publisher: 'Sunshine Books',
    year: 2011,
    pages: 320,
    isbn: '978-1890948221',
    price_range: '$25-30',
    format: 'Paperback',
    category: 'Puppies & Development',
    description: "Comprehensive puppy training manual designed for puppy class instructors but valuable for all trainers. The Martins (veterinarian and vet tech) provide: week-by-week curriculum, socialization protocols, handling exercises, basic obedience, problem prevention, and class management. Includes handouts for clients, training games, and troubleshooting sections. Force-free, science-based approach. Excellent framework for group puppy classes.",
    why_you_need_it: 'Complete puppy class curriculum that actually works. Essential for anyone teaching puppy classes.',
    best_for: 'Puppy class curriculum, comprehensive puppy training, instructor guide',
    purchase_url: 'https://www.amazon.com/Puppy-Start-Right-Foundation-Companion/dp/1890948225',
    audible_url: nil
  },
  {
    title: 'Before and After Getting Your Puppy: The Positive Approach to Raising a Happy, Healthy, and Well-Behaved Dog',
    author: 'Dr. Ian Dunbar',
    publisher: 'New World Library',
    year: 2004,
    pages: 256,
    isbn: '978-1577314554',
    price_range: '$14-18',
    format: 'Paperback, Kindle',
    category: 'Puppies & Development',
    description: "Classic puppy raising guide combining two of Dunbar's earlier books. Covers: choosing the right puppy, critical first days, socialization, bite inhibition, house training, basic manners, and common problems. Dunbar, veterinarian and founder of the Association of Professional Dog Trainers, pioneered puppy socialization classes and positive training methods. Readable, practical, and proven effective. Essential recommendation for puppy owners.",
    why_you_need_it: "Bite inhibition teaching is critical and often missed. Dunbar's protocol prevents adult dog bites.",
    best_for: 'Puppy selection, bite inhibition, socialization essentials',
    purchase_url: 'https://www.amazon.com/Before-After-Getting-Your-Puppy/dp/1577314557',
    audible_url: nil
  },

  # CATEGORY 17: RELATIONSHIP & COMMUNICATION
  {
    title: 'The Other End of the Leash: Why We Do What We Do Around Dogs',
    author: 'Patricia McConnell, PhD, CAAB',
    publisher: 'Ballantine Books',
    year: 2002,
    pages: 288,
    isbn: '978-0345446787',
    price_range: '$14-17',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Relationship & Communication',
    description: "Fascinating exploration of how humans and dogs miscommunicate due to being different species with different social systems. McConnell, an animal behaviorist, explains: primate vs. canine body language differences, how our movements and vocalizations confuse dogs, why dogs respond to certain training techniques, and how to bridge the communication gap. Deeply insightful and often funny. Changes how you see your own behavior around dogs.",
    why_you_need_it: 'Understanding how YOUR behavior affects dogs makes you a better trainer. Eye-opening perspective.',
    best_for: 'Handler skill development, understanding miscommunication, training insights',
    purchase_url: 'https://www.amazon.com/Other-End-Leash-What-Around/dp/034544678X',
    audible_url: 'https://www.audible.com/pd/The-Other-End-of-the-Leash-Audiobook/B002V0QUOC'
  },
  {
    title: 'For the Love of a Dog: Understanding Emotion in You and Your Best Friend',
    author: 'Patricia McConnell, PhD, CAAB',
    publisher: 'Ballantine Books',
    year: 2006,
    pages: 368,
    isbn: '978-0345477354',
    price_range: '$15-18',
    format: 'Paperback, Kindle, Audiobook',
    category: 'Relationship & Communication',
    description: "McConnell explores emotions in both dogs and humans - how they're similar, how they differ, and how they affect the training relationship. Covers: fear, anger, joy, happiness, love, and how understanding emotions improves training outcomes. Combines neuroscience, ethology, and personal stories. Deeply empathetic while remaining scientifically grounded. Important reading for trainers who want to work with the emotional side of behavior.",
    why_you_need_it: 'Behavior is driven by emotion. Understanding emotional foundations of behavior improves training success.',
    best_for: 'Emotional foundations of behavior, empathy development, fear/aggression work',
    purchase_url: 'https://www.amazon.com/Love-Dog-Understanding-Emotion-Friend/dp/0345477359',
    audible_url: 'https://www.audible.com/pd/For-the-Love-of-a-Dog-Audiobook/B002V8M1DO'
  },
  {
    title: 'How to Behave So Your Dog Behaves',
    author: 'Dr. Sophia Yin, DVM, MS',
    publisher: 'TFH Publications',
    year: 2004,
    pages: 256,
    isbn: '978-0793806423',
    price_range: '$18-23',
    format: 'Paperback',
    category: 'Relationship & Communication',
    description: "Yin's first major book emphasizing how handler behavior shapes dog behavior. Covers: learning theory, timing of rewards and corrections, body language, training exercises, and common behavior problems. Heavy emphasis on clear communication and consistency. Includes detailed photos demonstrating techniques. Yin's background as both veterinarian and animal behaviorist gives unique perspective on medical and behavioral issues.",
    why_you_need_it: "Many training 'failures' are handler errors. This book fixes the human side of the equation.",
    best_for: 'Handler skill development, timing improvement, training mechanics',
    purchase_url: 'https://www.amazon.com/Behave-Your-Dog-Behaves/dp/0793806429',
    audible_url: nil
  }
]

books_data.each do |book_attrs|
  book = Book.find_or_initialize_by(
    title: book_attrs[:title],
    is_default: true,
    user_id: nil
  )
  book.assign_attributes(book_attrs)
  book.save!
end

puts "✓ Seeded #{books_data.length} default books"
